version: "3.8"

services:
  rstudio:
    image: docker.synapse.org/syn22277123/i2b2-phi-dataset:1.2.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: i2b2-phi-dataset
    command: rstudio
    env_file:
      - .env
    volumes:
      - .:/home/rstudio/i2b2-phi-dataset:rw
    ports:
      - "${HOST_PORT}:8787"
